server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/CorsoFicarola
    password: emanuele2000
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update

